/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diffiehellman;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.interfaces.DHPublicKey;
import javax.crypto.spec.DHGenParameterSpec;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author Administrator
 */
public class Bob extends javax.swing.JFrame {

    /**
     * Creates new form Bob
     */
    public Bob() {
        initComponents();
    }
    
    KeyAgreement bobKeyAgree;
    PublicKey alicePubKey;
    SecretKey bobDesKey;
    Cipher bobCipher;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKhoaBOB = new javax.swing.JTextField();
        txtKhoaAlice = new javax.swing.JTextField();
        txtKhoaAB = new javax.swing.JTextField();
        txtMaHoaKAB = new javax.swing.JTextField();
        btnTaoKhoaB = new javax.swing.JButton();
        btnHienThiKA = new javax.swing.JButton();
        btnKhoaChung = new javax.swing.JButton();
        btnMaHoaKAB = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bob");

        jLabel2.setText("Khóa BOB:");

        jLabel3.setText("Khóa Alice:");

        jLabel4.setText("Khóa KAB:");

        jLabel5.setText("Mã hóa KAB:");

        btnTaoKhoaB.setText("Tạo khóa B");
        btnTaoKhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaBActionPerformed(evt);
            }
        });

        btnHienThiKA.setText("Hiển thị KA");
        btnHienThiKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiKAActionPerformed(evt);
            }
        });

        btnKhoaChung.setText("Khóa chung");
        btnKhoaChung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaChungActionPerformed(evt);
            }
        });

        btnMaHoaKAB.setText("Mã hóa KAB");
        btnMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaKABActionPerformed(evt);
            }
        });

        jButton5.setText("Mã hóa/Giải mã");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKhoaBOB, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoaAlice, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhoaAB, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMaHoaKAB)
                            .addComponent(btnKhoaChung)
                            .addComponent(btnTaoKhoaB)
                            .addComponent(btnHienThiKA))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKhoaBOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoKhoaB))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoaAlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienThiKA))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKhoaAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKhoaChung))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaHoaKAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoaKAB))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHienThiKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiKAActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fis = new FileInputStream("M:/A.pub");
            byte[] akeyP = new byte[fis.available()];
            fis.read(akeyP);
            fis.close();
            txtKhoaAlice.setText(akeyP.toString());
            
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_btnHienThiKAActionPerformed

    private void btnTaoKhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaBActionPerformed
        // TODO add your handling code here:
        try {
            boolean read = false;
            
            while (!read) {
                try {
                    FileInputStream fis = new FileInputStream("M:/A.pub");
                fis.close();    
                read = true;
                } catch (Exception ex) {
                    
                }    
            }
            
            FileInputStream fis = new FileInputStream("M:/A.pub");
            byte[] alicePubKeyEnc = new byte[fis.available()];
            fis.read(alicePubKeyEnc);
            fis.close();    
            KeyFactory bobKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(alicePubKeyEnc);
            alicePubKey = bobKeyFac.generatePublic(x509KeySpec);
            DHParameterSpec dhParamSpec = ((DHPublicKey) alicePubKey).getParams();
            System.out.println("Generate DH keypair ...");
            KeyPairGenerator bobKpairGen = KeyPairGenerator.getInstance("DH");
            bobKpairGen.initialize(dhParamSpec);
            KeyPair bobKpair = bobKpairGen.generateKeyPair();
            System.out.println("Initualizing KeyAgreement engine...");
            bobKeyAgree = KeyAgreement.getInstance("DH");
            bobKeyAgree.init(bobKpair.getPrivate());
            byte[] bobPubKeyEnc = bobKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("M:/B.pub");
            fos.write(bobPubKeyEnc);
            fos.close();
            txtKhoaBOB.setText(bobPubKeyEnc.toString());
            

        } catch (Exception ex) {
            
        }
        
        
        
    }//GEN-LAST:event_btnTaoKhoaBActionPerformed

    private void btnKhoaChungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaChungActionPerformed
        // TODO add your handling code here:
        try {
            bobKeyAgree.doPhase(alicePubKey, true);
            byte[] bobSharedSecret = bobKeyAgree.generateSecret();
            System.out.println("Khoa chung: Shared secret (DEBUG ONLY): " + CryptoUtil.toHexString(bobSharedSecret));
            txtKhoaAB.setText(CryptoUtil.toHexString(bobSharedSecret));
        } catch (Exception ex) {}
    }//GEN-LAST:event_btnKhoaChungActionPerformed

    private void btnMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaKABActionPerformed
        // TODO add your handling code here:
        try {
            bobKeyAgree.doPhase(alicePubKey, true);
            bobDesKey = bobKeyAgree.generateSecret("DES");
            txtMaHoaKAB.setText(bobDesKey.toString());
            
            BufferedWriter bw = null;
            String fileName = "M:\\KhoaB.txt";
            
            bw = new BufferedWriter(new FileWriter(fileName));
            
            bw.write(bobDesKey.toString());
            bw.close(); 
            
        } catch (Exception ex) {}
    }//GEN-LAST:event_btnMaHoaKABActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Bob des = new Bob();
        des.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiKA;
    private javax.swing.JButton btnKhoaChung;
    private javax.swing.JButton btnMaHoaKAB;
    private javax.swing.JButton btnTaoKhoaB;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKhoaAB;
    private javax.swing.JTextField txtKhoaAlice;
    private javax.swing.JTextField txtKhoaBOB;
    private javax.swing.JTextField txtMaHoaKAB;
    // End of variables declaration//GEN-END:variables
}
